### ISSUE TITLE
Only works if the resolver returns a promise

### ISSUE THREAD

**Issue by thebigredgeek** [lucasconstantino/graphql-resolvers#1]

**Comment by thebigredgeek** [comment]
https://github.com/lucasconstantino/graphql-resolvers/blob/master/src/combineResolvers.js#L15

**Comment by lucasconstantino** [comment]
Not really. The [tests](https://github.com/lucasconstantino/graphql-resolvers/blob/master/test/combineResolvers.test.js) quite many scenarios, and in fact most resolvers in the test do not return promises. Basically, the reducer is initialized with an [empty resolved promise](https://github.com/lucasconstantino/graphql-resolvers/blob/master/src/combineResolvers.js#L17), starting the promise chain.

The big "but" here is that `combineResolvers` *always* returns a promise, which might not be desired in some cases. Bot `graphql-js` and `graphql-tools` resolver specs receive promises just fine, in fact they wrap their resolver results in promises anyway, but if this helper method were to be used in other scenarios it would probably need some refactoring not to enforce promises when involved resolvers do not return promises. Meanwhile, it is much simpler a more elegant just to wrap the values - either error, undefineds, or true results.

**Comment by thebigredgeek** [comment]
Ah!  I missed that part!  Yeah, makes sense.
